/* This file is automatically generated by configure.  Do not modify by hand. */
/* Define if compiling with the default_modules module files.  */
#define USING_DEFAULT_MODULES_MODULE 1
 
/* Define if compiling with the snmpv3mibs module files.  */
#define USING_SNMPV3MIBS_MODULE 1
 
/* Define if compiling with the ucd_snmp module files.  */
#define USING_UCD_SNMP_MODULE 1
 
/* Define if compiling with the notification module files.  */
#define USING_NOTIFICATION_MODULE 1
 
/* Define if compiling with the notification-log-mib module files.  */
#define USING_NOTIFICATION_LOG_MIB_MODULE 1
 
/* Define if compiling with the target module files.  */
#define USING_TARGET_MODULE 1
 
/* Define if compiling with the agent_mibs module files.  */
#define USING_AGENT_MIBS_MODULE 1
 
/* Define if compiling with the agentx module files.  */
#define USING_AGENTX_MODULE 1
 
/* Define if compiling with the disman/event module files.  */
#define USING_DISMAN_EVENT_MODULE 1
 
/* Define if compiling with the disman/schedule module files.  */
#define USING_DISMAN_SCHEDULE_MODULE 1
 
/* Define if compiling with the utilities module files.  */
#define USING_UTILITIES_MODULE 1
 
/* Define if compiling with the host module files.  */
#define USING_HOST_MODULE 1
 
/* Define if compiling with the snmpv3/snmpEngine module files.  */
#define USING_SNMPV3_SNMPENGINE_MODULE 1
 
/* Define if compiling with the snmpv3/snmpMPDStats module files.  */
#define USING_SNMPV3_SNMPMPDSTATS_MODULE 1
 
/* Define if compiling with the snmpv3/usmStats module files.  */
#define USING_SNMPV3_USMSTATS_MODULE 1
 
/* Define if compiling with the snmpv3/usmUser module files.  */
#define USING_SNMPV3_USMUSER_MODULE 1
 
/* Define if compiling with the ucd-snmp/proc module files.  */
#define USING_UCD_SNMP_PROC_MODULE 1
 
/* Define if compiling with the ucd-snmp/versioninfo module files.  */
#define USING_UCD_SNMP_VERSIONINFO_MODULE 1
 
/* Define if compiling with the ucd-snmp/pass module files.  */
#define USING_UCD_SNMP_PASS_MODULE 1
 
/* Define if compiling with the ucd-snmp/pass_persist module files.  */
#define USING_UCD_SNMP_PASS_PERSIST_MODULE 1
 
/* Define if compiling with the ucd-snmp/disk_hw module files.  */
#define USING_UCD_SNMP_DISK_HW_MODULE 1
 
/* Define if compiling with the ucd-snmp/loadave module files.  */
#define USING_UCD_SNMP_LOADAVE_MODULE 1
 
/* Define if compiling with the agent/extend module files.  */
#define USING_AGENT_EXTEND_MODULE 1
 
/* Define if compiling with the ucd-snmp/errormib module files.  */
#define USING_UCD_SNMP_ERRORMIB_MODULE 1
 
/* Define if compiling with the ucd-snmp/file module files.  */
#define USING_UCD_SNMP_FILE_MODULE 1
 
/* Define if compiling with the ucd-snmp/dlmod module files.  */
#define USING_UCD_SNMP_DLMOD_MODULE 1
 
/* Define if compiling with the ucd-snmp/proxy module files.  */
#define USING_UCD_SNMP_PROXY_MODULE 1
 
/* Define if compiling with the ucd-snmp/logmatch module files.  */
#define USING_UCD_SNMP_LOGMATCH_MODULE 1
 
/* Define if compiling with the ucd-snmp/memory module files.  */
#define USING_UCD_SNMP_MEMORY_MODULE 1
 
/* Define if compiling with the ucd-snmp/vmstat module files.  */
#define USING_UCD_SNMP_VMSTAT_MODULE 1
 
/* Define if compiling with the notification/snmpNotifyTable module files.  */
#define USING_NOTIFICATION_SNMPNOTIFYTABLE_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_MODULE 1
 
/* Define if compiling with the notification/snmpNotifyFilterProfileTable module files.  */
#define USING_NOTIFICATION_SNMPNOTIFYFILTERPROFILETABLE_MODULE 1
 
/* Define if compiling with the notification-log-mib/notification_log module files.  */
#define USING_NOTIFICATION_LOG_MIB_NOTIFICATION_LOG_MODULE 1
 
/* Define if compiling with the target/snmpTargetAddrEntry module files.  */
#define USING_TARGET_SNMPTARGETADDRENTRY_MODULE 1
 
/* Define if compiling with the target/snmpTargetParamsEntry module files.  */
#define USING_TARGET_SNMPTARGETPARAMSENTRY_MODULE 1
 
/* Define if compiling with the target/target module files.  */
#define USING_TARGET_TARGET_MODULE 1
 
/* Define if compiling with the target/target_counters module files.  */
#define USING_TARGET_TARGET_COUNTERS_MODULE 1
 
/* Define if compiling with the agent/nsTransactionTable module files.  */
#define USING_AGENT_NSTRANSACTIONTABLE_MODULE 1
 
/* Define if compiling with the agent/nsModuleTable module files.  */
#define USING_AGENT_NSMODULETABLE_MODULE 1
 
/* Define if compiling with the agent/nsDebug module files.  */
#define USING_AGENT_NSDEBUG_MODULE 1
 
/* Define if compiling with the agent/nsCache module files.  */
#define USING_AGENT_NSCACHE_MODULE 1
 
/* Define if compiling with the agent/nsLogging module files.  */
#define USING_AGENT_NSLOGGING_MODULE 1
 
/* Define if compiling with the agent/nsVacmAccessTable module files.  */
#define USING_AGENT_NSVACMACCESSTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteScalars module files.  */
#define USING_DISMAN_EVENT_MTESCALARS_MODULE 1
 
/* Define if compiling with the disman/event/mteTrigger module files.  */
#define USING_DISMAN_EVENT_MTETRIGGER_MODULE 1
 
/* Define if compiling with the disman/event/mteTriggerTable module files.  */
#define USING_DISMAN_EVENT_MTETRIGGERTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteTriggerDeltaTable module files.  */
#define USING_DISMAN_EVENT_MTETRIGGERDELTATABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteTriggerExistenceTable module files.  */
#define USING_DISMAN_EVENT_MTETRIGGEREXISTENCETABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteTriggerBooleanTable module files.  */
#define USING_DISMAN_EVENT_MTETRIGGERBOOLEANTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteTriggerThresholdTable module files.  */
#define USING_DISMAN_EVENT_MTETRIGGERTHRESHOLDTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteTriggerConf module files.  */
#define USING_DISMAN_EVENT_MTETRIGGERCONF_MODULE 1
 
/* Define if compiling with the disman/event/mteEvent module files.  */
#define USING_DISMAN_EVENT_MTEEVENT_MODULE 1
 
/* Define if compiling with the disman/event/mteEventTable module files.  */
#define USING_DISMAN_EVENT_MTEEVENTTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteEventSetTable module files.  */
#define USING_DISMAN_EVENT_MTEEVENTSETTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteEventNotificationTable module files.  */
#define USING_DISMAN_EVENT_MTEEVENTNOTIFICATIONTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteEventConf module files.  */
#define USING_DISMAN_EVENT_MTEEVENTCONF_MODULE 1
 
/* Define if compiling with the disman/event/mteObjects module files.  */
#define USING_DISMAN_EVENT_MTEOBJECTS_MODULE 1
 
/* Define if compiling with the disman/event/mteObjectsTable module files.  */
#define USING_DISMAN_EVENT_MTEOBJECTSTABLE_MODULE 1
 
/* Define if compiling with the disman/event/mteObjectsConf module files.  */
#define USING_DISMAN_EVENT_MTEOBJECTSCONF_MODULE 1
 
/* Define if compiling with the disman/schedule/schedCore module files.  */
#define USING_DISMAN_SCHEDULE_SCHEDCORE_MODULE 1
 
/* Define if compiling with the disman/schedule/schedConf module files.  */
#define USING_DISMAN_SCHEDULE_SCHEDCONF_MODULE 1
 
/* Define if compiling with the disman/schedule/schedTable module files.  */
#define USING_DISMAN_SCHEDULE_SCHEDTABLE_MODULE 1
 
/* Define if compiling with the utilities/override module files.  */
#define USING_UTILITIES_OVERRIDE_MODULE 1
 
/* Define if compiling with the host/hr_system module files.  */
#define USING_HOST_HR_SYSTEM_MODULE 1
 
/* Define if compiling with the host/hr_device module files.  */
#define USING_HOST_HR_DEVICE_MODULE 1
 
/* Define if compiling with the host/hr_other module files.  */
#define USING_HOST_HR_OTHER_MODULE 1
 
/* Define if compiling with the host/hr_proc module files.  */
#define USING_HOST_HR_PROC_MODULE 1
 
/* Define if compiling with the host/hr_print module files.  */
#define USING_HOST_HR_PRINT_MODULE 1
 
/* Define if compiling with the host/hr_disk module files.  */
#define USING_HOST_HR_DISK_MODULE 1
 
/* Define if compiling with the host/hr_partition module files.  */
#define USING_HOST_HR_PARTITION_MODULE 1
 
/* Define if compiling with the host/hrh_storage module files.  */
#define USING_HOST_HRH_STORAGE_MODULE 1
 
/* Define if compiling with the host/hrh_filesys module files.  */
#define USING_HOST_HRH_FILESYS_MODULE 1
 
/* Define if compiling with the host/hrSWInstalledTable module files.  */
#define USING_HOST_HRSWINSTALLEDTABLE_MODULE 1
 
/* Define if compiling with the host/hrSWRunTable module files.  */
#define USING_HOST_HRSWRUNTABLE_MODULE 1
 
/* Define if compiling with the util_funcs/header_generic module files.  */
#define USING_UTIL_FUNCS_HEADER_GENERIC_MODULE 1
 
/* Define if compiling with the util_funcs module files.  */
#define USING_UTIL_FUNCS_MODULE 1
 
/* Define if compiling with the util_funcs/restart module files.  */
#define USING_UTIL_FUNCS_RESTART_MODULE 1
 
/* Define if compiling with the ucd-snmp/pass_common module files.  */
#define USING_UCD_SNMP_PASS_COMMON_MODULE 1
 
/* Define if compiling with the util_funcs/header_simple_table module files.  */
#define USING_UTIL_FUNCS_HEADER_SIMPLE_TABLE_MODULE 1
 
/* Define if compiling with the hardware/fsys module files.  */
#define USING_HARDWARE_FSYS_MODULE 1
 
/* Define if compiling with the hardware/memory module files.  */
#define USING_HARDWARE_MEMORY_MODULE 1
 
/* Define if compiling with the hardware/cpu module files.  */
#define USING_HARDWARE_CPU_MODULE 1
 
/* Define if compiling with the notification/snmpNotifyTable_data module files.  */
#define USING_NOTIFICATION_SNMPNOTIFYTABLE_DATA_MODULE 1
 
/* Define if compiling with the header_complex module files.  */
#define USING_HEADER_COMPLEX_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_data_storage module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_DATA_STORAGE_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_MODULE 1
 
/* Define if compiling with the notification/snmpNotifyFilterProfileTable_data module files.  */
#define USING_NOTIFICATION_SNMPNOTIFYFILTERPROFILETABLE_DATA_MODULE 1
 
/* Define if compiling with the target/snmpTargetAddrEntry_data module files.  */
#define USING_TARGET_SNMPTARGETADDRENTRY_DATA_MODULE 1
 
/* Define if compiling with the target/snmpTargetParamsEntry_data module files.  */
#define USING_TARGET_SNMPTARGETPARAMSENTRY_DATA_MODULE 1
 
/* Define if compiling with the host/data_access/hr_disk_linux module files.  */
#define USING_HOST_DATA_ACCESS_HR_DISK_LINUX_MODULE 1
 
/* Define if compiling with the host/data_access/hr_partition_other module files.  */
#define USING_HOST_DATA_ACCESS_HR_PARTITION_OTHER_MODULE 1
 
/* Define if compiling with the host/data_access/swinst module files.  */
#define USING_HOST_DATA_ACCESS_SWINST_MODULE 1
 
/* Define if compiling with the host/data_access/swrun module files.  */
#define USING_HOST_DATA_ACCESS_SWRUN_MODULE 1
 
/* Define if compiling with the host/hrSWRunPerfTable module files.  */
#define USING_HOST_HRSWRUNPERFTABLE_MODULE 1
 
/* Define if compiling with the hardware/fsys/hw_fsys module files.  */
#define USING_HARDWARE_FSYS_HW_FSYS_MODULE 1
 
/* Define if compiling with the hardware/fsys/fsys_mntent module files.  */
#define USING_HARDWARE_FSYS_FSYS_MNTENT_MODULE 1
 
/* Define if compiling with the hardware/memory/hw_mem module files.  */
#define USING_HARDWARE_MEMORY_HW_MEM_MODULE 1
 
/* Define if compiling with the hardware/memory/memory_linux module files.  */
#define USING_HARDWARE_MEMORY_MEMORY_LINUX_MODULE 1
 
/* Define if compiling with the hardware/cpu/cpu module files.  */
#define USING_HARDWARE_CPU_CPU_MODULE 1
 
/* Define if compiling with the hardware/cpu/cpu_linux module files.  */
#define USING_HARDWARE_CPU_CPU_LINUX_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_interface module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_INTERFACE_MODULE 1
 
/* Define if compiling with the snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_data_access module files.  */
#define USING_SNMP_NOTIFICATION_MIB_SNMPNOTIFYFILTERTABLE_SNMPNOTIFYFILTERTABLE_DATA_ACCESS_MODULE 1
 
/* Define if compiling with the host/data_access/swinst_apt module files.  */
#define USING_HOST_DATA_ACCESS_SWINST_APT_MODULE 1
 
/* Define if compiling with the host/data_access/swrun_procfs_status module files.  */
#define USING_HOST_DATA_ACCESS_SWRUN_PROCFS_STATUS_MODULE 1
 
